config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  #resources :requests
  #patch  '/request', to: 'requests#change_open_status'
  resources :requests do
    member do
      patch "change_open_status"
    end
  end

  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post   '/apply',   to: 'request_applications#create'
  delete '/withdraw',   to: 'request_applications#destroy'
  patch  '/change_application_status', to: 'request_applications#change_application_status'
end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "creator_id"

    has_many :request_applications, class_name: "Request_Application", foreign_key: "request_id"
    has_many :applicants, class_name: "User", through: :request_applications, dependent: :destroy

    validates(:title, presence: true, length: {:maximum => 50})
    validates(:startDateTime, presence: true)
    validates(:endDateTime, presence: true)
    validates(:reward, presence: true)
    validate(:check_start_end_dates)
    validates(:location, presence: true)
    validates(:recruitment_number, presence: true)
    validates(:contact, presence: true)
    validates(:creator_id, presence: true)
    validates(:open, inclusion: {in: [true, false]})


    def check_start_end_dates
        return false if self.startDateTime.nil? || self.endDateTime.nil?
        if self.startDateTime >= self.endDateTime
            errors.add(:endDateTime, ": 終了は開始日時より後の日時のみ設定可能です。")
        end
    end

    def request_status_inJap
        if self.open
            return "募集中"
        elsif !self.open
            return "募集終了"
        else
            return "失敗"
        end
    end

    def get_applieds
        Request_Application.select{ |a| a.status == "applied" && a.request_id == self.id }.map{ |r| r.applicant }
    end

    def get_workings
        Request_Application.select{ |a| a.status == "working" && a.request_id == self.id }.map{ |r| r.applicant }
    end

    def get_completeds
        Request_Application.select{ |a| a.status == "completed" && a.request_id == self.id }.map{ |r| r.applicant }
    end

    def get_rejecteds
        Request_Application.select{ |a| a.status == "rejected" && a.request_id == self.id }.map{ |r| r.applicant }
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    @request = current_user.created_requests.create!(request_params)
    @user = @request.creator
    if !@request.nil?
      flash[:success] = "新規リクエストが作成されました。"
      redirect_to request_path(@request)
    else
      flash.now[:danger] = "新規リクエストが作成失敗。"
      render 'new'
    end
  end

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @user = @request.creator
  end

  def destroy
    @request = current_user.created_requests.find(params[:id])
    if @request.destroy
      flash[:success] = "募集を削除しました。"
      redirect_to current_user
    else
      flash.now[:danger] = "募集削除に失敗しました。"
      render 'show'
    end
  end

  def change_open_status
    @request = current_user.created_requests.find(params[:id])
    @user = @request.creator
    if @request.update(open: !@request.open)
      flash[:success] = "募集ステータスを変更しました。"
      redirect_to request_path(@request)
    else
      flash.now[:danger] = "募集ステータスの変更に失敗しました。"
      render 'show'
    end
  end

  private
    def request_params
      params.require(:request).permit(:title, :startDateTime, :endDateTime, :location, :requirements, :reward, :contact, :recruitment_number, :request_detail)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
    def check_start_end_dates
        return false if (params[:startDataTime].nil? || params[:endDateTime].nil?) || (params[:startDataTime] >= params[:endDateTime])
    end
end

app/views/requests/_applicant.html.erb
<div class="row">
  <div class="col-md-6 Crequest-details-applicant-name">
    <%= link_to applicant.name, applicant %>
  </div>
  <% if current_status == "applied" %>
    <div class="col-md-3">
      <%= button_to "採用", change_application_status_path(request:@request, applicant:applicant, new_status:"working"), method: :patch, data: { confirm: "この応募者を採用しますか?" }, class: 'btn btn-outline-success Cbtn' %>  
    </div>
    <div class="col-md-3">
      <%= button_to "不採用", change_application_status_path(request:@request, applicant:applicant, new_status:"rejected"), method: :patch, data: { confirm: "この応募者を不採用にしますか?" }, class: 'btn btn-outline-danger Cbtn' %>
    </div>
  <% elsif current_status == "working" %>
    <div class="col-md-3">
      <%= button_to "完了", change_application_status_path(request:@request, applicant:applicant, new_status:"completed"), method: :patch, data: { confirm: "この作業を終了しますか?" }, class: 'btn btn-outline-success Cbtn' %>
    </div>
    <div class="col-md-3">
      <%= button_to "中止", change_application_status_path(request:@request, applicant:applicant, new_status:"rejected"), method: :patch, data: { confirm: "この作業を中止しますか?" }, class: 'btn btn-outline-danger Cbtn' %>
    </div>
  <% end %>
</div>

app/views/requests/_applications_status.html.erb
<div class="Crequest-detail-application-status-frame">
    <div class="row">
        <div class="col-md-12">
            <h2>応募状況</h2>
        </div>
    </div>

    <div class="row Cbottom-margin">
        <div class="col-md-12 Cbottom-margin">
            <% applieds = @request.get_applieds %>
            <h4 class="Chorizontal-center"><u>応募者 (<%= applieds.count %>名)</u></h4>
            <% if applieds.any? %>
                <%= render partial: 'requests/applicant', collection: applieds, as: :applicant, locals: {current_status: "applied"} %>
            <% end %>
        </div>

        <div class="col-md-12 Cbottom-margin">
            <% workings = @request.get_workings %>
            <h4 class="Chorizontal-center"><u>取り組み中 (<%= workings.count %>名)</u></h4>
            <% if workings.any? %>
                <%= render partial: 'requests/applicant', collection: workings, as: :applicant, locals: {current_status: "working"} %>
            <% end %>
        </div>

        <div class="col-md-12 Cbottom-margin">
            <% completeds = @request.get_completeds %>
            <h4 class="Chorizontal-center"><u>終了済み (<%= completeds.count %>名)</u></h4>
            <% if completeds.any? %>
                <%= render partial: 'requests/applicant', collection: completeds, as: :applicant, locals: {current_status: "completed"} %>
            <% end %>
        </div>

        <div class="col-md-12 Cbottom-margin">
            <% rejecteds = @request.get_rejecteds %>
            <h4 class="Chorizontal-center"><u>不採用・解雇 (<%= rejecteds.count %>名)</u></h4>
            <% if rejecteds.any? %>
                <%= render partial: 'requests/applicant', collection: rejecteds, as: :applicant, locals: {current_status: "rejected"} %>
            <% end %>
        </div>
    </div>
</div>

app/views/requests/index.html.erb
<% provide(:title, '募集を探す') %>
<div class="row">
  <div class="col-md-3">
    <div class="card Ccard-frame">
      <article class="card-group-item">
        <header class="card-header"><h6 class="title">カテゴリー</h6></header>
        <div class="filter-content">
          <div class="list-group list-group-flush">
            <a href="#" class="list-group-item">プログラミング<span class="float-right badge badge-light round">4</span> </a>
            <a href="#" class="list-group-item">外国語<span class="float-right badge badge-light round">2</span>  </a>
            <a href="#" class="list-group-item">スポーツ<span class="float-right badge badge-light round">3</span>  </a>
            <a href="#" class="list-group-item">農業<span class="float-right badge badge-light round">12</span>  </a>
            <a href="#" class="list-group-item">etc...<span class="float-right badge badge-light round">?</span>  </a>
          </div>  <!-- list-group .// -->
        </div>
      </article>
    </div>
  </div>
  <div class="col-md-8">
    <div class="row Crow-bottom-space">
      <div class="col-md-12">
        <h3>全ての募集 (<%= @requests.count %>件)</h3>
      </div>
      <% if @requests.any? %>
        <%= render partial: 'shared/request', collection: @requests%>
      <% end %>
    </div>
</div>

app/views/requests/new.html.erb
<% provide(:title, 'リクエスト作成') %>
<div class="Cform-frame"> 
  <div class="col-md-12">
    <h1>新規リクエスト作成</h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= form_for(@request, url: requests_path, html:{ class: "Cform-for rounded-lg border" }) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <h5 class="Cno-margin-bottom">リクエストタイトル</h5>
        <%= f.text_field :title, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">開始日時</h5>
        <%= f.datetime_field :startDateTime, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">終了日時</h5>
        <%= f.datetime_field :endDateTime, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">場所</h5>
        <%= f.text_field :location, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">条件・必要なスキル</h5>
        <%= f.text_field :requirements, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">報酬</h5>
        <%= f.text_field :reward, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">募集人数</h5>
        <%= f.number_field :recruitment_number, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">連絡先</h5>
        <%= f.text_field :contact, class: 'Cform-control' %>
        <h5 class="Cno-margin-bottom">詳細・メッセージ</h5>
        <%= f.text_area :request_detail, class: 'Cform-control' %>
        <div class="Chorizontal-center">
          <%= f.submit "リクエスト作成", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
</div>

app/views/requests/show.html.erb
<% provide(:title, @request.title) %>

<div class="row">
    <div class="col-md-3">
        <%= render partial: 'shared/profile' %>
    </div>
    <div class ="col-md-6 border Crequest-detail-frame">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <img src="http://fusic.co.jp/img/system/fusic_ogp.jpg" class="Crequest-detail-pic border border-dark"></img>
            </div>
        </div>
        <div class="Crequest-detail-content">
            <h2 class="Crequest-detail-title"><%= @request.title %></h1>
            <table class="table table-gray">
                <tbody>
                    <tr>
                        <td>開始日時</td>
                        <td><%= @request.startDateTime %></td>
                    </tr>
                    <tr>
                        <td>終了日時</td>
                        <td><%= @request.endDateTime %></td>
                    </tr>
                    <tr>
                        <td>場所</td>
                        <td><%= @request.location %></td>
                    </tr>
                    <tr>
                        <td>報酬</td>
                        <td><%= @request.reward %></td>
                    </tr>
                    <tr>
                        <td>条件など</td>
                        <td><%= @request.requirements %></td>
                    </tr>
                    <tr>
                        <td>募集人数</td>
                        <td><%= @request.recruitment_number %></td>
                    </tr>
                    <tr>
                        <td>連絡先</td>
                        <td><%= @request.contact %></td>
                    </tr>
                    <tr>
                        <td>詳細・メッセージ</td>
                        <td><%= @request.request_detail %></td>
                    </tr>
                    <% if current_user.id == @request.creator_id %>
                        <tr>
                            <td>募集状況</td>
                            <td><strong class="Ccolor-red"><%= @request.request_status_inJap %></strong></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="row">
                <% if current_user.id == @request.creator_id %>
                    <div class="col-md-4">
                        <button type="button" class="btn btn-primary Cbtn" disabled>編集</button>
                    </div>
                    <div class="col-md-4">
                        <%= button_to "募集ステータス変更", change_open_status_request_path(@request), method: :patch, data: { confirm: "募集ステータスを変更しますか?" }, class: 'btn btn-primary Cbtn' %>
                    </div>
                    <div class="col-md-4">
                        <%= button_to "募集削除", request_path(@request), method: :delete, data: { confirm: "この募集を削除しますか?" }, class: 'btn btn-outline-danger Cbtn' %>
                    </div>
                <% elsif !@request.open && current_user.application_status(@request) == "notapplied" %>
                    <div class="col-md-12 Cbottom-margin">
                        <button type="button" class="btn btn-primary Cbtn" disabled>募集終了</button>
                    </div>
                <% elsif @request.open && current_user.application_status(@request) == "notapplied" %>
                    <div class="col-md-12 Cbottom-margin">
                        <%= button_to "応募", apply_path(request: @request), method: :post, data: { confirm: "この募集に応募しますか?" }, class: 'btn btn-warning Cbtn' %>
                    </div>
                <% elsif current_user.application_status(@request) == "rejected" %>
                    <div class="col-md-12 Cbottom-margin">
                        <button type="button" class="btn btn-lg btn-primary Cbtn" disabled>今回は不採用となりました</button>   
                    </div> 
                <% elsif current_user.application_status(@request) == "applied" %>
                    <div class="col-md-12 Cbottom-margin">
                        <%= button_to "辞退", withdraw_path(request: @request), method: :delete, data: { confirm: "この応募を辞退しますか?" }, class: 'btn btn-primary Cbtn' %>
                    </div>
                <% elsif current_user.application_status(@request) == "working" %>
                    <div class="col-md-12 Cbottom-margin">
                        <button type="button" class="btn btn-primary Cbtn" disabled>取り組み中</button>
                    </div>
                <% elsif current_user.application_status(@request) == "completed" %>
                    <div class="col-md-12 Cbottom-margin">
                        <button type="button" class="btn btn-primary Cbtn" disabled>作業完了</button>
                    </div>
                <% else %>
                    <div class="col-md-12 Cbottom-margin">    
                        <button type="button" class="btn btn-warning Cbtn" disabled>うまくif使えてないぞー</button>
                    </div>
                <% end %>
            </div>
            <% if current_user.id == @request.creator_id %>
                <hr class="Chr"/>
                <%= render partial: 'requests/applications_status' %>
            <% end %>
        </div>
    </div>
</div>