config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  #resources :requests
  #patch  '/request', to: 'requests#change_open_status'
  resources :requests do
    member do
      patch "change_open_status"
    end
  end

  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post   '/apply',   to: 'request_applications#create'
  delete '/withdraw',   to: 'request_applications#destroy'
  patch  '/change_application_status', to: 'request_applications#change_application_status'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg justify-content-end Cnav">
  <ul class="navbar-nav">
      <li class="nav-item Cnav-item">
        <a class="nav-link"><%= link_to "Home", root_path, { class: "CtextColor" } %></a>
      </li>
    <% if logged_in? %>
      <li class="nav-item Cnav-item">
        <a class="nav-link"><%= link_to "募集を探す", requests_path, { class: "CtextColor" } %></a>
      </li>
      <li class="nav-item Cnav-item">
        <a class="nav-link"><%= link_to "リクエスト追加", new_request_path, { class: "CtextColor" } %></a>
      </li>
      <li class="nav-item dropdown Cnav-item Cdropdown">
        <a class="nav-link dropdown-toggle CtextColor" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><%= link_to "マイページ", current_user %></a>
          <a class="dropdown-item" href="#"><%= link_to "アカウント設定", '#' %></a>
          <div class="dropdown-divider"></div>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </div>
      </li>
    <% else %>
      <li class="nav-item Cnav-item">
        <a class="nav-link"><%= link_to "ログイン", login_path, { class: "CtextColor" } %></a>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>